[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
finai_budget = "DzSFtsfM8tdSEzxxV5mnJFiBVLNFZrirDGH2QR38SqRb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/olanrewaju/.config/solana/id.json"


[scripts]
test = "pnpm exec mocha -t 1000000 'packages/contracts/finai-budget/tests/**/*.cjs'"
